### PR TITLE
Performance of `(+,-,*,/)(::TaylorScalar,::Number)`: easy short path ? 

### PR DESCRIPTION
**Pull request by lrnv**
Hey, 

The current implementation of `*(::TaylorScalar,::Number)` in your package promotes the scalar to a TaylorScalar as so : 

````julia
for op in (:+, :-, :*, :/)
    @eval @inline $op(a::TaylorScalar, b::Number) = $op(promote(a, b)...)
    @eval @inline $op(a::Number, b::TaylorScalar) = $op(promote(a, b)...)
end
````
and then uses the full blown multiplication of taylorScalars: 
````julia
@generated function *(a::TaylorScalar{T, N}, b::TaylorScalar{T, N}) where {T, N}
    return quote
        va, vb = value(a), value(b)
        @inbounds TaylorScalar($([:(+($([:($(binomial(i - 1, j - 1)) * va[$j] *
                                           vb[$(i + 1 - j)]) for j in 1:i]...)))
                                  for i in 1:N]...))
    end
end
````

Although very general and elegant, this seems super wasteful as a bunch of multiplications by 0 will occur and still take runtime. 

````julia
t = TaylorScalar(rand(20)...)
x = rand(10)
@btime Ref(t) .* x; # 922 ns
@btime (TaylorScalar(t.value * xi) for xi in x) # 58 ns
````

and so a specific function would be nice. Same thing occurs for +,-,/ if i read your code correclty. 

As i am not well versed in the @eval shananigans, the code I produced is quite ugly and has non-ncessary loops, but I could not fix that myself ;)

Please tell me what you think, I got a 40% speedup in my application with this.

### CODE REVIEW

**Comment by lrnv** [comment]
I'm sorry i cleaned up the work and forced-pushed onto my branch, so if you want to pickup from there you can of course. 

I did not understood your graphs, where should i see the performance increase in the scalar operations ?

**Comment by lrnv** [comment]
Hey 

I added convenience functions to be able to multiply and/or divide  TaylorScalar{T,N}'s with different Ts. This was missing and is very helpfull for me. 

Indeed, I need to derivate through TaylorScalar's machinery: So I end up with types of the form `TaylorScalar{ForwardDiff{...},N}`.

**Comment by ToucheSir** [comment]
> That's because Zygote is too weak to infer type through your `[2:end]` semantics

Instead of tuple slicing, you can use `ntuple(i -> mytup[i + 2], length(mytup) - 2)`. It's uglier but is more likely to be type stable. We use this pattern across a bunch of FluxML code.

**Comment by lrnv** [comment]
Hey sorry i did not catch up on your responses, i did not see them... 

I am quite swampped right now so i have no time to fix this PR, sorry. You may fix it yourself, or simply wait a few more weeks for me to do it ;)

**Comment by tansongchen** [comment]
I will be working on this during the summer, however with a different approach. I am currently adding chunking support to this package like ForwardDiff.jl, something like this

```julia
struct TaylorScalar{V, N, K}
  primal::V
  partials::NTuple{K, NTuple{N, V}}
end
```

where K is the order, and N is the chunk size as in ForwardDiff.jl. `partials` will be a polynomial consists of tuples, not numbers.

Based on this, we have easy access to the primal value via `getfield`, so won't face the same issue as we currently have.

**Comment by lrnv** [comment]
Thanks for feedback @tansongchen. For me the real issue is #61 and until this is dealt with I cannot switch from TaylorSeries.jl to TaylorDiff.jl.

**Comment by lrnv** [comment]
closed in favor of #81

**Pull request closed without merging**
